language: php
php:
  - '7.0'
install:
  - composer install --dev
before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - cp phpunit.xml.dist phpunit.xml
script:
  - ./vendor/bin/simple-phpunit